---
title: "Computation of main coefficients"
author: "Derumigny, A. , Guyonvarch Y. & Girard, L."
date: \today
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Computation of coefficients for Theorem 1 and 2


## Computation of $e_1(\varepsilon)$

```{r}
# Definition of the functions
e_1n = function(eps, hasSkewness = TRUE) {
  
  P_1n = ( 144 + 48*eps + 4*eps^2 ) / 576
  if (hasSkewness){
    P_1n = P_1n + ( 96*sqrt(2*eps) + 32*eps + 16*sqrt(2)*eps^(3/2) ) / 576
  }
  b = eps^2*( 1/6 + 2 * P_1n / (1-3*eps)^2 )
  return(exp(b))
}

# print(e_1n(eps = 0.1))
# print(e_1n(eps = 0.1, hasSkewness = FALSE))

th1_coeff_K4n <- function(eps) {0.327 * (1/12 + 1 / (4 * (1-3*eps)^2 ) )}
th1_coeff_lambda3n_2 <- function (eps) {0.037 * e_1n(eps = eps)}

# Changes for theorem 2
e_3n = function(eps) { exp( eps^2 / 6 + eps^2 / (2 * (1-3*eps)^2) ) }
th2_coeff_lambda3n_2 <- function(eps) {0.037 * e_3n(eps = eps)}
```

## Computation of the corresponding coefficients

```{r}
eps = c(0.2, 0.1, 0.05, 0.02)
df_coefficients = data.frame(
  eps = eps,
  Coef.K4n = th1_coeff_K4n(eps),
  Coef.lambda3n.2.in.th1 = th1_coeff_lambda3n_2(eps),
  Coef.lambda3n.2.in.th2 = th2_coeff_lambda3n_2(eps)
)

df_coefficients
```

