---
title: "Computation of kappa"
author: "Derumigny, A. , Guyonvarch Y. & Girard, L."
date: \today
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
# Function to compute a_n (cf article)

t1 <- 0.64 # universal constant from paper

compute_an <- function(n, K3) {
  
  build_an_1 <- 2 * t1 * pi * sqrt(n) / (K3+1)
  build_an_2 <- 16 * pi^3 * n^2 / (K3 + 1)^4
  
  return( min(build_an_1, build_an_2)/sqrt(n) )
}
```


# Exponential and normal distributions


```{r}
# Setting parameters
Nrep = 100000

K4_exp <- 9
K4_gauss <- 3
```


```{r}
# Computation of absolute third order moment
K3_exp <- 2.31
K3_gauss <- 2^(3/2) * gamma(2) / sqrt(pi)
```


```{r}
# Compute kappa_n for exp and standard normal

carac_exp_at_an <- 1 / sqrt(1 + compute_an(n = 100000, K3 = K3_exp)^2)
print(carac_exp_at_an)

carac_gauss_at_an <- exp( - compute_an(n = 5000, K3 = K3_gauss)^2/2)
print(carac_gauss_at_an)
```


# Student distribution

```{r}
# Function to evaluate the characteristic function of 
# the Student distribution at some point of interest (here a_n)

stud_carac_fun <- function(n, nu) {
  Nrep = 100000
  sigma <- sqrt(nu/(nu-2))
  K4 <- 6/(nu-4)+3
  an <- compute_an(n=n, K3 = mean(abs(scale(rt(Nrep, df = nu)))^3) )
  temp1 <- besselK(nu = nu/2, x = sqrt(nu)*abs(an)/sigma)
  temp2 <- (sqrt(nu)*abs(an)/sigma)^(nu/2) / (gamma(nu/2)*2^(nu/2-1))
  
  return(temp1 * temp2)
}

# Compute kappa_n for the Student distribution

stud_carac_fun(n = 5000, nu = 8)
stud_carac_fun(n = 5000, nu = 5)
```

